
info:
  version: 1.0.0

spring:
  application:
    name: albeniz

# Change Actuator base URI
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    httptrace:
      enabled: true

server:
  error.whitelabel.enabled: false
  servlet:
    context-path: /albeniz/actuator
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true